### ISSUE TITLE
--/FT-XXX - Descriptive Title

### ISSUE THREAD

**Issue by ChampiMagic** [ChampiMagic/project-template#1]
## These issues must be closed to start this task

*(if none, delete this section)*
- [ ] *mention any issue on which this task is dependent (use the "#" sign)*

## Package to implement 

*(if none, delete this section)*
- name of the packages to be used

## UI to implement

*(if none, delete this section)*

*Add screnshots of the UIs to implement*

## Tasks *

- [ ] first requirement to complete this task
- [ ] second requirement to complete this task

## Keep in mind 

*(if none, delete this section)*
- soem other details on how to resolve this issue
